import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { HeaderAction } from "./navber";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#091140" }}>
        <HeaderAction
          links={[
            { link: "dd", label: "d" },
            { link: "dd", label: "d" },
            { link: "dd", label: "d" },
          ]}
        />
        {children}
      </body>
    </html>
  );
}
